syntax = "proto3";

option java_package = "se.gcom.middleware.communicationModule";
option java_multiple_files = true;

service CommunicationService{
  rpc SendMessage(Message) returns (Ack);
}

message Message {
  oneof content {
    ChatMessage chatMessage = 1;
    GroupMembership groupMembership = 2;
  }
}

message ChatMessage {
  string messageId = 1;
  string senderId = 2;
  string groupId= 3;
  string payload = 4;
  map<string, int32> vectorClock = 5;
}

message GroupMembership{
  string messageId = 1;
  string senderId = 2;
  string groupId = 3;
  bool joining = 4;
}

message Ack {
  bool success = 1;
  string errorMessage = 2;
  oneof details {
    DataAck data = 3;
    MembershipAck membership = 4;
  }
}

message MembershipAck {
  int32 viewId = 1;
  repeated string members = 2;
  map<string, int32> vectorClock = 3;
  bool isCausal = 4;
}

message DataAck { }