package se.gcom.app.debug;

public enum DebugEventType {
    PROCESS_STARTED,
    MESSAGE_CREATED,
    MESSAGE_DELIVERED,

    VECTOR_CLOCK_UPDATED,
    MESSAGE_HELD_BACK,

    NETWORK_SEND,
    NETWORK_RECEIVE,
    NETWORK_ACK,
    NETWORK_NO_RESPONSE
}
